[package]
name = "rust-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.0.0", features = ["derive"] }
colored = "2.1.0"
indicatif = "0.17.8"
log = "0.4.22"
